version: '3.7'

services:
  api:
    depends_on:
      - db
    image: foodie
    build: .
    restart: "no"
    ports:
      - "10000:8080"
    networks:
      - backend
  db:
    image: mongo:4
    restart: unless-stopped
    command: mongod
    volumes:
      - ./docker/mongo/:/docker-entrypoint-initdb.d/
      - db:/data/db
    ports:
      - "10001:27017"
    networks:
      - backend
    environment:
      - MONGO_INITDB_DATABASE=foodie
      - MONGO_INITDB_ROOT_USERNAME=foodie
      - MONGO_INITDB_ROOT_PASSWORD=foodie
networks:
  backend:
volumes:
  db: