logging:
  level:
    net.sandrohc: INFO

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  batch:
    job.enabled: false
    initialize-schema: always
  flyway:
    sql-migration-prefix: ''
    sql-migration-separator: '-'