logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    net.sandrohc: DEBUG

spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://foodie:foodie@localhost:27017/foodie