logging:
  level:
#    org.hibernate:
#      SQL: DEBUG
#      type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.jdbc.core:
#      JdbcTemplate: DEBUG
#      StatementCreatorUtils: TRACE
    net.sandrohc: DEBUG

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:10001/foodie
    username: foodie
    password: foodie
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        generate_statistics: false
    hibernate:
      ddl-auto: update # none/create/update
  flyway:
    sql-migration-prefix: ''
    sql-migration-separator: '-'