logging:
    level:
#        org.hibernate:
#            SQL: DEBUG
#            type.descriptor.sql.BasicBinder: TRACE
#        org.springframework.jdbc.core:
#            JdbcTemplate: DEBUG
#            StatementCreatorUtils: TRACE
        net.sandrohc: DEBUG

spring:
    profiles:
        active: dev
    datasource:
        ## PostgreSQL
        url: jdbc:postgresql://localhost:5432/postgres
        username: mmms
        password: mmms

    jpa:
#        show-sql: true
#        properties:
#            hibernate:
#                format_sql: false
        hibernate:
            ddl-auto: create

    batch:
        initialize-schema: always
