name: Foodie

on: [push, pull_request]

jobs:
  # CI
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Tests
        run: ./gradlew test
      - name: Build
        run: ./gradlew bootJar
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: build/libs/

  # CD
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: app
          path: build/libs/
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t foodie -t ${{ secrets.DOCKER_USER }}/foodie:latest .
      - name: Push
        run: docker push ${{ secrets.DOCKER_USER }}/foodie:latest
